CREATE TABLE IF NOT EXISTS `IT202-F2024-Games` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `game_title` VARCHAR(255),
    `platforms` VARCHAR(255),
    `genre` VARCHAR(255),
    `release_date` VARCHAR(255),
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE(`game_title`)
)