CREATE TABLE IF NOT EXISTS `IT202-F2024-Games` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `game_title` STRING NOT NULL,
    `publisher` STRING NOT NULL,
    `genre` STRING NOT NULL,
    `release_year` INT NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE(`symbol`, `latest`)
)